spring:
  profiles:
    active:
      - EN
      - dog
      - prod
guru:
  username: YmlUserName
  password: YmlPassword
  jdbcurl: YmlUrl

---
spring:
  config:
    activate:
      on-profile: prod
guru:
  username: YmlProdUserName
  password: YmlProdPassword
  jdbcurl: YmlProdUrl

