spring:
  profiles:
    active:
      - EN
      - dog
      - dev
guru:
  username: YmlUserName
  password: YmlPassword
  jdbcurl: YmlUrl

guru1:
  username: YmlGuru1UserName
  password: YmlGuru1Password
  jdbcurl: YmlGuru1lUrl

---
spring:
  config:
    activate:
      on-profile: prod
guru:
  username: YmlProdUserName
  password: YmlProdPassword
  jdbcurl: YmlProdUrl

guru1:
  username: YmlProdGuru1UserName
  password: YmlProdGuru1Password
  jdbcurl: YmlProdGuru1lUrl